#!/bin/bash
set -ux

#
# git bk - create doug/bk configured to current branch
#

echo "Backing up..."
git branch --delete --force doug/bk
git push origin --delete feature/doug/bk
git branch doug/bk
git push -u origin feature/doug/bk
git log --oneline -3 develop..doug/bk
