#!/bin/bash
set -eu

#
# git doug - cleanup the doug/branches & other cruft
#

color_reset='\033[0m'
green='\033[0;32m'

git checkout develop
git pull

echo -e "Prune origin...${green}"
git remote prune origin
echo -en "${color_reset}"

echo -e "Deleting local merged branches ...${green}"
git branch -a --merged | grep -E "^\s*doug" | xargs -n1 git branch -d
echo -en "${color_reset}"

echo -e "Deleting patch checkouts ...${green}"
git branch | grep "change-" | xargs -n1 git branch -D
echo -en "${color_reset}"

# echo "Deleting merged branches on origin ..."
# git branch -a --merged | grep "remotes/origin/doug" |
#     cut -d"/" -f4 | xargs -I BRANCH git push origin ":doug/BRANCH"
