#!/bin/bash
set -ux

#
# git bk - create doug/bk configured to current branch
#

echo "Backing up..."
git branch --delete --force doug/bk
git push origin --delete doug/bk
git branch doug/bk
git push -u origin doug/bk
git log --oneline -3 main..doug/bk
